# Generated by Django 3.0.2 on 2020-06-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_subject_credit_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='labmanual',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='oldquestion',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='oldquestion',
            name='year',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='practisequestion',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='credit_hours',
            field=models.CharField(default=3, max_length=10, verbose_name='Credit Hours'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='nature',
            field=models.CharField(choices=[('Theory + Practical', 'Theory + Practical'), ('Theory', 'Theory'), ('Practical', 'Practical')], max_length=100, verbose_name='Subject Nature'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(max_length=200, verbose_name='Subject Name'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_number',
            field=models.CharField(max_length=20, verbose_name='Subject code'),
        ),
    ]
