# Generated by Django 3.0.2 on 2020-06-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='device_id',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
